[options]
admin_passwd = $pbkdf2-sha512$600000$sbYWwpjTGkNIqXVu7d3bOw$C8JBjNmdxfjc1pTTXxmEpyGH9WvJNuPHEfJJUBlHobQK7KmGP3ZHNIKdTvR6lroobe2xPTHlUoRx7Wwfcmi4Hg
db_host = db
db_user = odoo
db_password = myodoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

